const AM1_SAMPLE="Shipment ID,Placa,Data auditoria,ID da rota,Estado,Rep auditoria\nDEMO-AM1-001,DEMO-A,15/01/2026 08:00:00,A01_AM1 | DEMO-ROTA-A,Faltante,Operador A\nDEMO-AM1-002,DEMO-A,15/01/2026 08:05:00,A01_AM1 | DEMO-ROTA-A,Faltante,Operador A\nDEMO-AM1-003,DEMO-B,15/01/2026 08:10:00,B02_AM1 | DEMO-ROTA-B,A mais,Operador B\nDEMO-AM1-004,DEMO-B,15/01/2026 08:15:00,B02_AM1 | DEMO-ROTA-B,Correto,Operador B\nDEMO-AM1-005,DEMO-A,15/01/2026 08:20:00,A01_AM1 | DEMO-ROTA-A,Correto,Operador A\nDEMO-AM1-001,DEMO-A,15/01/2026 09:00:00,A01_AM1 | DEMO-ROTA-A,Correto,Operador A\nDEMO-AM1-006,DEMO-C,15/01/2026 14:00:00,C03_PM1 | DEMO-ROTA-C,Faltante,Operador C\nDEMO-AM1-007,DEMO-A,16/01/2026 08:00:00,A01_AM1 | DEMO-ROTA-A,Faltante,Operador A\nDEMO-AM1-008,DEMO-A,16/01/2026 08:05:00,A01_AM1 | DEMO-ROTA-A,A mais,Operador A\nDEMO-AM1-009,DEMO-B,16/01/2026 08:10:00,B02_AM1 | DEMO-ROTA-B,Correto,Operador B\n";
(function(){
 'use strict';const $=id=>document.getElementById(id);let records=[];
 function render(){const latest=$('latest').checked,cycle=$('cycle').value,date=$('date').value;const stats=AM1Core.count(AM1Core.select(records,date,cycle,latest));$('metrics').replaceChildren();
  for(const [label,key] of [['Total','total'],['Faltantes','missing'],['A mais','extra'],['Corretos','correct'],['Outros','other'],['Divergências','divergences']]){const card=document.createElement('div');card.className='metric';card.textContent=label;const number=document.createElement('strong');number.textContent=stats[key];card.append(number);$('metrics').append(card);}
  $('mode').textContent=latest?'Última auditoria por pacote + data + ciclo. Em empate de horário, prevalece a última linha importada.':'Cada linha válida conta como um registro de auditoria, incluindo repetições.';
  $('summary').replaceChildren();for(const r of AM1Core.summary(records,cycle,latest)){const tr=document.createElement('tr');for(const key of ['date','total','missing','extra','correct','other','divergences']){const td=document.createElement('td');td.textContent=r[key];tr.append(td);}$('summary').append(tr);}$('export').disabled=!records.length;
 }
 function load(texts){try{let next=[],invalid=0;for(const text of texts){const result=AM1Core.parse(text);next.push(...result.accepted);invalid+=result.rejected.length;}records=next;
  for(const [id,values]of [['date',[...new Set(records.map(r=>r.date))].sort((a,b)=>a.split('/').reverse().join('').localeCompare(b.split('/').reverse().join('')))],['cycle',[...new Set(records.map(r=>r.cycle))].sort()]]){$(id).replaceChildren();for(const value of values){const opt=document.createElement('option');opt.value=value;opt.textContent=value;$(id).append(opt);}}
  if([...$('cycle').options].some(o=>o.value==='AM1'))$('cycle').value='AM1';$('message').textContent=`${records.length} linhas válidas • ${invalid} linhas rejeitadas • ${texts.length} arquivo(s).`;render();
 }catch(e){$('message').textContent='Erro: '+e.message+' A última análise válida foi preservada.';}}
 $('sample').onclick=()=>load([AM1_SAMPLE]);
 $('import').onclick=async()=>{if(!$('files').files.length){$('message').textContent='Selecione ao menos um CSV.';return;}try{load(await Promise.all([...$('files').files].map(f=>f.text())));}catch(e){$('message').textContent='Não foi possível ler os arquivos: '+e.message;}};
 for(const id of ['date','cycle','latest'])$(id).onchange=render;
 $('export').onclick=()=>{const rows=AM1Core.summary(records,$('cycle').value,$('latest').checked);const csv='\uFEFF'+[['Data','Total','Faltantes','A mais','Corretos','Outros','Divergencias'],...rows.map(r=>[r.date,r.total,r.missing,r.extra,r.correct,r.other,r.divergences])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='am1-resumo-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 load([AM1_SAMPLE]);
})();
